# Builds rpgdemo.gb from src and art; -Verify compares a fresh build with the committed files.
param([switch]$Offline, [switch]$Verify)
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$demoRoot = $PSScriptRoot
$root = Split-Path (Split-Path $demoRoot -Parent) -Parent
$version = 'v1.0.4'
$archiveUrl = "https://github.com/gbdev/rgbds/releases/download/$version/rgbds-win64.zip"
$archiveHash = 'BD1D7E386F290AFD57F4EA9A7353BFCD4AE10884A94C5C1F2FC42A75DB7F97E6'
$toolHashes = [ordered]@{
    'rgbasm.exe' = '26017C1B2FE7F4255963C644EE3E76A619A5E3BAFA97EAF78DDD142411C64427'
    'rgblink.exe' = 'B59DF72CF2A9CD9FDE529F8E564C43E9E3BE2326D19C2B1781C1FF8EBA4BD28D'
    'rgbfix.exe' = '5E558415ACB76751E1D7970CC778456AEAA40F30C9768E669751BD3AD773F88A'
    'rgbgfx.exe' = '8AD164FB42CB626188CED7FD24648BD237F307660585E90DD6402942765D15F4'
}
$cacheRoot = Join-Path $root '.cache/rgbds'
$toolRoot = Join-Path $cacheRoot $version
New-Item -ItemType Directory -Force $cacheRoot, $toolRoot | Out-Null

function Assert-Hash([string]$Path, [string]$Expected) {
    if (!(Test-Path -LiteralPath $Path) -or (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash -ne $Expected) {
        throw "Missing file or SHA-256 mismatch: $Path"
    }
}

function Invoke-Tool([string]$Name, [string[]]$Arguments) {
    & (Join-Path $toolRoot $Name) @Arguments
    if ($LASTEXITCODE -ne 0) { throw "$Name failed with exit code $LASTEXITCODE." }
}

$archive = Join-Path $cacheRoot 'rgbds-win64.zip'
if (!(Test-Path -LiteralPath $archive)) {
    if ($Offline) { throw "Offline cache is missing: $archive" }
    Invoke-WebRequest -Uri $archiveUrl -OutFile "$archive.download" -TimeoutSec 60
    Assert-Hash "$archive.download" $archiveHash
    Move-Item -LiteralPath "$archive.download" -Destination $archive -Force
}
Assert-Hash $archive $archiveHash
Add-Type -AssemblyName System.IO.Compression.FileSystem
foreach ($tool in $toolHashes.GetEnumerator()) {
    $path = Join-Path $toolRoot $tool.Key
    if (!(Test-Path -LiteralPath $path) -or (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash -ne $tool.Value) {
        $zip = [IO.Compression.ZipFile]::OpenRead($archive)
        try {
            $entry = $zip.GetEntry($tool.Key)
            if ($null -eq $entry) { throw "Archive entry is missing: $($tool.Key)" }
            [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, "$path.download", $true)
        } finally { $zip.Dispose() }
        Assert-Hash "$path.download" $tool.Value
        Move-Item -LiteralPath "$path.download" -Destination $path -Force
    }
}

# Convert the pictures to tiles; object sheets use magenta for the transparent colour 0.
$work = Join-Path $root '.cache/rpgdemo-build'
Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $work | Out-Null
$art = Join-Path $demoRoot 'art'
$bgColors = '#FFFFFF,#AAAAAA,#555555,#000000'
$objColors = '#FF00FF,#FFFFFF,#AAAAAA,#000000' # OBP0: white, light, black
$logoColors = '#FF00FF,#FFFFFF,#AAAAAA,#555555' # OBP1: white, light, dark

function Convert-Sheet([string]$Name, [string]$Colors, [string[]]$Options = @()) {
    $output = Join-Path $work ($Name + '.2bpp')
    Invoke-Tool 'rgbgfx.exe' (@('-c', $Colors, '-o', $output) + $Options + @((Join-Path $art ($Name + '.png'))))
    return (Get-Item -LiteralPath $output).Length / 16
}

Convert-Sheet 'font' $bgColors | Out-Null
Convert-Sheet 'ui' $bgColors | Out-Null
# Title landscape and logo share BG IDs 00-7F: unique tiles, the logo's after the landscape's.
$titleTiles = Convert-Sheet 'title' $bgColors @('-u', '-t', (Join-Path $work 'title.tilemap'))
$logoTiles = Convert-Sheet 'logo' $bgColors @('-u', '-b', "$titleTiles", '-t', (Join-Path $work 'logo.tilemap'))
if ($titleTiles + $logoTiles -gt 128) { throw "Title pictures need $($titleTiles + $logoTiles) tiles (at most 128)." }
Convert-Sheet 'logo-obj' $logoColors @('-Z') | Out-Null
Convert-Sheet 'heroes-walk' $objColors @('-Z') | Out-Null
Convert-Sheet 'effects' $objColors @('-Z') | Out-Null
Convert-Sheet 'heroes-face' $bgColors | Out-Null
Convert-Sheet 'heroes-back' $bgColors | Out-Null
Convert-Sheet 'enemies' $bgColors | Out-Null
Convert-Sheet 'battle' $bgColors | Out-Null
Convert-Sheet 'keypad' $bgColors | Out-Null
Set-Content -LiteralPath (Join-Path $work 'art.inc') -Encoding ascii -Value @(
    '; Generated by Build.ps1 from art/*.png.',
    "DEF TITLE_TILES EQU $titleTiles",
    "DEF LOGO_TILES EQU $logoTiles"
)

# Assemble in the scratch folder; only the ROM and symbol file are kept in the repository.
$source = Join-Path $demoRoot 'src'
$object = Join-Path $work 'rpgdemo.o'
$rom = Join-Path $work 'rpgdemo.gb'
$symbols = Join-Path $work 'rpgdemo.sym'
$map = Join-Path $work 'rpgdemo.map'
Invoke-Tool 'rgbasm.exe' @('-Wall', '-Wextra', '-I', $source, '-I', $work, '-o', $object, (Join-Path $source 'rpgdemo.asm'))
Invoke-Tool 'rgblink.exe' @('-d', '-t', '-p', '0xFF', '-n', $symbols, '-m', $map, '-o', $rom, $object)
# Write the header title and checksums only, leaving out the Nintendo logo.
Invoke-Tool 'rgbfix.exe' @('-f', 'hg', '-p', '0xFF', '-t', 'USAGI QUEST', $rom)

$outputs = @('rpgdemo.gb', 'rpgdemo.sym')
if ($Verify) {
    foreach ($name in $outputs) {
        $built = Join-Path $work $name
        $committed = Join-Path $demoRoot $name
        if (!(Test-Path -LiteralPath $committed)) { throw "Committed file is missing: $committed" }
        $expected = (Get-FileHash -LiteralPath $committed -Algorithm SHA256).Hash
        if ((Get-FileHash -LiteralPath $built -Algorithm SHA256).Hash -ne $expected) {
            throw "Rebuilt $name differs from the committed file."
        }
        Write-Output "$name reproduced: SHA-256 $($expected.ToLowerInvariant())"
    }
} else {
    foreach ($name in $outputs) {
        Copy-Item -LiteralPath (Join-Path $work $name) -Destination (Join-Path $demoRoot $name) -Force
        Write-Output "$name SHA-256 $((Get-FileHash -LiteralPath (Join-Path $demoRoot $name) -Algorithm SHA256).Hash.ToLowerInvariant())"
    }
}
Write-Output "Tiles: title $titleTiles, logo $logoTiles. RGBDS $version ($archiveUrl) verified."
