<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>GonFox.GameBoy.Platform</RootNamespace>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GonFox.GameBoy.Platform.Shared\GonFox.GameBoy.Platform.Shared.csproj" />
    <ProjectReference Include="..\GonFox.GameBoy.Platform.Windows\GonFox.GameBoy.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\GonFox.GameBoy.Core.Tests\TestRom.cs" Link="TestRom.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Roms\BackgroundDemo\background-demo.gb" Link="background-demo.gb" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Roms\SoundCheck\sound-check.gb" Link="sound-check.gb" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Roms\MegaDemo\megademo.gb" Link="megademo.gb" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Roms\RpgDemo\rpgdemo.gb" Link="rpgdemo.gb" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
